SELECT  volume,
        id,
        name,
        sex,
        height,
        build,
        dentition,
        special_peculiarities,
        TO_CHAR(date_of_birth, 'YYYY-MM-DD'),
        place_of_birth,
        place_of_residence,
        residence,
        religion,
        childhood_status,
        marital_status,
        number_of_children,
        occupation,
        occupation_2,
        occupation_3,
        military_service,
        literacy,
        education,
        criminal_history,
        crime,
        TO_CHAR(sentence_begins, 'YYYY-MM-DD'),
        TO_CHAR(sentence_expires, 'YYYY-MM-DD'),
        prison_term_day,
        ransome,
        associates,
        degree_of_crime,
        degree_of_punishment,
        notes,
        arrest_site
        from lta_main where username = session['current_user']
        limit 1;


